language: python
python:
  - "2.7"
  - "3.6"

install: 
# - pip install -r requirements.txt
  - python setup.py install

script: py.test python

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

env:
    CXX=g++-5

