language: python
python:
  - "3.6"

install: 
# - pip install -r requirements.txt
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - cd googletest/googletest/make && env CXXFLAGS=-std=c++14 make
  - python setup.py install

script: py.test python

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

env:
    CXX=g++-5

