package:
  name: fixfmt

  version: 0.5.7

about:
  home: https://github.com/alexhsamuel/fixfmt
  license: Apache 2.0
  license_file: LICENSE

source:
  git_rev: 0.5.7
  git_url: https://github.com/alexhsamuel/fixfmt.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

build:
  script: python setup.py install

test:
  imports:
    - fixfmt

