package:
  name: pyinstrument
  version: "0.13.1"

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD
  license_file: LICENSE

source:
  git_rev: v0.13.1
  git_url: https://github.com/joerick/pyinstrument.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

build:
  script: CXX=clang++ LDFLAGS=-static-libstdc++ make install

test:
  imports:
    - pyinstrument

