package:
  name: fixfmt
  version: 0.10.2

about:
  home: https://github.com/alexhsamuel/fixfmt
  license: Apache 2.0
  license_file: LICENSE

source:
  git_rev: 0.10.2
  git_url: https://github.com/alexhsamuel/fixfmt.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.6

build:
  script: python setup.py install

test:
  imports:
    - fixfmt

