package:
  name: fixfmt

  version: 0.1.3

about:
  home: https://github.com/alexhsamuel/fixfmt
  license: BSD
  license_file: LICENSE

source:
  git_rev: 0.1.3
  git_url: https://github.com/alexhsamuel/fixfmt.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

build:
  # For now, build with static libstdc++ to avoid the runtime dependency.
  # GCC 5.4 has some issues with our code.
  script: CXX=clang++ LDFLAGS=-static-libstdc++ make install

test:
  imports:
    - fixfmt

